version: "3.6"
services:
  php-apache:
    image: docker.io/zvanoz/php-7-0-dev:20240805
    container_name: local.zvanoz-php-syntax-7-0
    env_file:
      - ./.env
    ports:
      - "${EXT_PORT}:80"
    user: "${UID}:${GID}"
    volumes:
      - ./www:/var/www
      - ./xdebug-2.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini