version: "3.6"
services:
  php-apache:
    image: local/php-syntax-8-0
    container_name: local.php-syntax-8-0
    build:
      context: ./
      dockerfile: Dockerfile
    env_file:
      - ./.env
    ports:
      - "${EXT_PORT}:80"
    user: "${UID}:${GID}"
    volumes:
      - ./www:/var/www
      - ./xdebug-3.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini